### ISSUE TITLE
Could not find a declaration file for module 'iview'. 'D:/work/test/vue-iview-ts/node_modules/iview/dist/iview.js' implicitly has an 'any' type.   Try `npm install @types/iview` if it exists or add a new declaration (.d.ts) file containing `declare module 'iview';`

### ISSUE THREAD

**Issue by justnowanna** [yangdan8/vue-iview-ts#1]
![image](https://user-images.githubusercontent.com/7813730/45286898-90072f80-b519-11e8-985b-b9ce4db41ff1.png)

`git clone`下来之后 按照教程执行就报这个错误了，是什么原因呢？我看到`node_modules/iview/dist`下面有types文件夹 为什么还是说找不到呢？虽然项目是正常启动了

**Comment by justnowanna** [comment]
![image](https://user-images.githubusercontent.com/7813730/45287745-a0200e80-b51b-11e8-95ea-216ab64af3ec.png)

另外补充一下 楼主的很多.d.ts文件会有一些问题，比如这个应该是boolean | string

**Comment by yangdan8** [comment]
要用最新的代码,或者修改   ...\node_modules\iview\package.json  中157行
"typings": "types/index.d.ts",
修改为
"typings": "dist/types/index.d.ts",

以及修改  ...\node_modules\iview\dist\types\iview.components.d.ts文件中第68行和69行
    locale: (l) => void;
    i18n: (fn) => void;
修改为
    locale: (l:any) => void;
    i18n: (fn:any) => void;

**Comment by yangdan8** [comment]
string不能分配给boolean的问题 是官方api修改后导致的,我提交pr给作者吧

**Comment by justnowanna** [comment]
@yangdan8 感谢回复，如果去修改node_modules 那么后面就没法更新最新的版本了，iview那边会去处理这种问题吗？

**Comment by yangdan8** [comment]
iview已经更新发布
